/*
  2012-07-23 14:00 GMT
  source/coffee/main.coffee > scripts/main.js
  
  created by Grifo
*/
// Generated by CoffeeScript 1.3.3
(function(){var e,t;e=function(e){return[].slice.call(document.querySelectorAll(e))},t=function(e){return document.querySelector(e)},e("a[rel=external]").forEach(function(e){return e.addEventListener("click",function(e){return e.preventDefault(),window.open(e.target.href||e.target.parentNode.href)})})}).call(this);