/*
  2012-08-23 21:39 GMT
  source/coffee/main.coffee > scripts/main.js
  
  created by Grifo
*/
// Generated by CoffeeScript 1.3.3
(function(){var e,t,n,r;e=function(e){return[].slice.call(document.querySelectorAll(e))},t=function(e){return document.querySelector(e)},e("a[rel=external]").forEach(function(e){return e.addEventListener("click",function(e){return e.preventDefault(),window.open(e.target.href||e.target.parentNode.href)})}),r=function(e,t){e=e[""+t+"Sibling"];while(e&&e.nodeType!==1)e=e[""+t+"Sibling"];return e},n=t(".board .item-current"),t(".nav").addEventListener("click",function(e){var i,s,o,u,a;console.log("go go"),e.preventDefault(),i=e.target.className,u={right:"previous",left:"next"}[i],o=r(n,u);if(!o)return;return n.className="item-"+u,o.className="item-current",s=o.getAttribute("data-image"),s&&(o.style.backgroundImage="url("+s+")",o.removeAttribute("data-background-image")),window.history.pushState({},document.title,o.getAttribute("data-url")),a=r(o,"previous"),a?t(".nav .right").outerHTML='<a href="'+a.getAttribute("data-url")+'" class="right">&raquo;</a>':t(".nav .right").outerHTML='<span class="right">&raquo;</span>',a=r(o,"next"),a?t(".nav .left").outerHTML='<a href="'+a.getAttribute("data-url")+'" class="left">&laquo;</a>':t(".nav .left").outerHTML='<span class="left">&laquo;</span>',n=o})}).call(this);